### ISSUE TITLE
Update react-bootstrap

### ISSUE THREAD

**Issue by igreulich** [BoomTownROI/boomstrap-react#35]
We need to update the version of react-bootstrap we are using as the basis for Boomstrap-React.

We want to use the collapse plugin, among other things.

@mfunkie You mentioned there being a hold up because of the way the ```Modal``` component was rewritten, and that you needed to rewrite some things to accommodate.

**Comment by mfunkie** [comment]
We're about to cut a 0.25 release of react-bootstrap.  I can start investigating when that happens.

**Comment by igreulich** [comment]
Cool deal

On Tue, Aug 25, 2015 at 11:22 AM, Mark Funk <notifications@github.com>
wrote:

> We're about to cut a 0.25 release of react-bootstrap. I can start
> investigating when that happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BoomTownROI/boomstrap-react/issues/35#issuecomment-134622746>
> .
>



-- 
*Ian Greulich*
Senior Software Engineer
BoomTownROI.com <http://www.boomtownroi.com/>

<http://boomtownroi.com/>
<http://boomtownroi.com/blog/post/hat-trick-boomtown-recognized-for-third-consecutive-year-inc-5005000-list>
