### ISSUE TITLE
Problem minifying.

### ISSUE THREAD

**Issue by igreulich** [BoomTownROI/boomstrap-react#6]
A now reverted upgrade to lodash, caused the build to break, during uglifying. From what we can tell, the offender is uglify, not lodash, but the problem was surfaced by lodash.

@mfunkie will be experimenting with uglify options to see if there is anything we can do to prevent the error.

Currently the issue is only with lodash 3.x.

**Comment by mfunkie** [comment]
Turns out this is actually caused by the second minification that happens in ScriptBundle.  I'm going to add some flags to allow us to skip this in the future.

**Comment by igreulich** [comment]
Script Bundles are the worst.

**Comment by mfunkie** [comment]
Just a note here, lodash was a dependency of Babel (now a dev dependency) so maybe we can look at updating Babel again.

**Comment by igreulich** [comment]
I will take a look at that.

On Tue, Aug 18, 2015 at 9:55 AM, Mark Funk <notifications@github.com> wrote:

> Just a note here, lodash was a dependency of Babel (now a dev dependency)
> so maybe we can look at updating Babel again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BoomTownROI/boomstrap-react/issues/6#issuecomment-132216281>
> .
>



-- 
*Ian Greulich*
Senior Software Engineer
BoomTownROI.com <http://www.boomtownroi.com/>

<http://boomtownroi.com/>
<http://boomtownroi.com/blog/post/hat-trick-boomtown-recognized-for-third-consecutive-year-inc-5005000-list>
